blank_issues_enabled: false
contact_links:
  - name: GetAPet Discord
    url: https://withgetapet/discord
    about: Join our Discord for general questions as well as direct contact with the developers
