name: Feature Request
description: Have an idea for an improvement to GetAPet? Your ideas are always welcome here
title: "[Feature]: GetAPet needs [...]"
labels: ["feature request"]
assignees:
  - withGetAPet/reviewers
body:
  - type: markdown
    attributes:
      value: |
        ### **Thank you for taking the time to fill out this Feature Request!**
        Please provide as much information as possible. To make sure we have all the details we need to get started, please fill out the form below.
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: idea
    attributes:
      label: Tell us about your Wish
      description: |
        Describe the behavior you are looking for, pitch an idea, or make a suggestion for improvement.
    validations:
      required: true
  - type: input
    id: bugrelation
    attributes:
      label: Is your feature related to a bug
      description: |
        Refer to a an existing bug, you can use `#bugid`
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Have you thought about alternative solutions or ways of implementation? Do you have an idea for how this could be a reality? Let us know!
  - type: textarea
    id: info
    attributes:
      label: Additional Info
      description: |
        Provide additional information or links to resources that may be of assistance in the creation process.
    validations:
      required: false
  - type: checkboxes
    id: participation
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request to implement this
          required: false
  - type: checkboxes
    id: disclaimer
    attributes:
      label: Disclaimer
      description: I have checked that this has not been suggested before
      options:
        - label: I agree
          required: true
